// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by generate_problem_mapper.dart
//
// To regenerate, run: dart run scripts/generate_problem_mapper.dart

import 'dart:convert';
import 'package:chopper/chopper.dart';

import 'package:cent16/core/domain/failures/failure.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/server.exception.dart';
import 'package:cent16/core/domain/failures/local/accessdenied.cache.failure.dart';
import 'package:cent16/core/domain/failures/local/notfound.cache.failure.dart';
import 'package:cent16/core/domain/failures/local/readfailed.cache.failure.dart';
import 'package:cent16/core/domain/failures/local/writefailed.cache.failure.dart';
import 'package:cent16/core/domain/failures/remote/badrequest.failure.dart';
import 'package:cent16/core/domain/failures/remote/conflict.failure.dart';
import 'package:cent16/core/domain/failures/remote/default.server.failure.dart';
import 'package:cent16/core/domain/failures/remote/forbidden.failure.dart';
import 'package:cent16/core/domain/failures/remote/internalserver.failure.dart';
import 'package:cent16/core/domain/failures/remote/notfound.failure.dart';
import 'package:cent16/core/domain/failures/remote/unauthorized.failure.dart';
import 'package:cent16/core/domain/failures/remote/validation.server.failure.dart';
import 'package:cent16/core/infrastructure/exceptions/local/accessdenied.cache.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/local/notfound.cache.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/local/readfailed.cache.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/local/writefailed.cache.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/badrequest.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/conflict.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/default.server.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/forbidden.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/internalserver.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/notfound.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/unauthorized.exception.dart';
import 'package:cent16/core/infrastructure/exceptions/remote/validation.server.exception.dart';
import 'package:cent16/modules/auth/domain/failures/accessdenied.failure.dart';
import 'package:cent16/modules/auth/domain/failures/accountinactive.failure.dart';
import 'package:cent16/modules/auth/domain/failures/accountnotverified.failure.dart';
import 'package:cent16/modules/auth/domain/failures/otpattemptslimit.failure.dart';
import 'package:cent16/modules/auth/domain/failures/otpexpiration.failure.dart';
import 'package:cent16/modules/auth/domain/failures/usernotloggedin.failure.dart';
import 'package:cent16/modules/auth/infrastructure/exceptions/accessdenied.exception.dart';
import 'package:cent16/modules/auth/infrastructure/exceptions/accountinactive.exception.dart';
import 'package:cent16/modules/auth/infrastructure/exceptions/accountnotverified.exception.dart';
import 'package:cent16/modules/auth/infrastructure/exceptions/otpattemptslimit.exception.dart';
import 'package:cent16/modules/auth/infrastructure/exceptions/otpexpiration.exception.dart';
import 'package:cent16/modules/auth/infrastructure/exceptions/usernotloggedin.exception.dart';

/// Auto-generated mapper for converting between exceptions and failures.
///
/// This class provides methods to:
/// - Convert HTTP responses to typed exceptions
/// - Convert exceptions to failures for use in repositories
class ProblemMapper {
  ProblemMapper._();

  /// Converts HTTP Response to typed Exception.
  ///
  /// Maps the Problem Details title field to the appropriate exception type.
  static ServerException toException(Response response) {
    final data = _parseProblemDetails(response.body);
    final title = data['title'] as String? ?? 'Exception';

    switch (title) {
      case 'AccessDeniedException':
        return AccessDeniedException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'AccessDeniedException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'AccountInactiveException':
        return AccountInactiveException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'AccountInactiveException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'AccountNotVerifiedException':
        return AccountNotVerifiedException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'AccountNotVerifiedException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'BadRequestException':
        return BadRequestException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'BadRequestException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'ConflictException':
        return ConflictException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'ConflictException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'DefaultException':
        return DefaultException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'DefaultException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'ForbiddenException':
        return ForbiddenException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'ForbiddenException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'InternalServerException':
        return InternalServerException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'InternalServerException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'NotFoundException':
        return NotFoundException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'NotFoundException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'OtpAttemptsLimitException':
        return OtpAttemptsLimitException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'OtpAttemptsLimitException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'OtpExpirationException':
        return OtpExpirationException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'OtpExpirationException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'UnauthorizedException':
        return UnauthorizedException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'UnauthorizedException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'UserNotLoggedInException':
        return UserNotLoggedInException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'UserNotLoggedInException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      case 'ValidationException':
        return ValidationException(
          type: data['type'] as String? ?? 'about:blank',
          title: data['title'] as String? ?? 'ValidationException',
          detail: data['detail'] as String? ?? '',
          instance: data['instance'] as String?,
          extensions: data['extensions'] as Map<String, dynamic>?,
        );

      default:
        return DefaultException(
          type: 'about:blank',
          title: title,
          detail: data['detail'] as String? ?? 'An unexpected error occurred',
          instance: data['instance'] as String?,
          extensions: data,
        );
    }
  }

  /// Converts Exception to Failure.
  ///
  /// Maps exception instances to their corresponding failure types.
  /// Supports both remote (server) and local (cache) exceptions.
  static Failure toFailure(Exception exception) {
    // Local/Cache exceptions
    if (exception is ReadFailedCacheException) {
      return ReadFailedCacheFailure(
        message: exception.detail,
        instance: exception.instance,
      );
    }

    if (exception is WriteFailedCacheException) {
      return WriteFailedCacheFailure(
        message: exception.detail,
        instance: exception.instance,
      );
    }

    if (exception is NotFoundCacheException) {
      return NotFoundCacheFailure(
        message: exception.detail,
        instance: exception.instance,
      );
    }

    if (exception is AccessDeniedCacheException) {
      return AccessDeniedCacheFailure(
        message: exception.detail,
        instance: exception.instance,
      );
    }

    // Remote/Server exceptions
    if (exception is AccessDeniedException) {
      return AccessDeniedFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is AccountInactiveException) {
      return AccountInactiveFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is AccountNotVerifiedException) {
      return AccountNotVerifiedFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is BadRequestException) {
      return BadRequestFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is ConflictException) {
      return ConflictFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is DefaultException) {
      return DefaultFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is ForbiddenException) {
      return ForbiddenFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is InternalServerException) {
      return InternalServerFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is NotFoundException) {
      return NotFoundFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is OtpAttemptsLimitException) {
      return OtpAttemptsLimitFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is OtpExpirationException) {
      return OtpExpirationFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is UnauthorizedException) {
      return UnauthorizedFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is UserNotLoggedInException) {
      return UserNotLoggedInFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    if (exception is ValidationException) {
      return ValidationFailure(
        type: exception.type,
        title: exception.title,
        message: exception.detail,
        instance: exception.instance,
        extensions: exception.extensions,
      );
    }

    // Fallback for unmapped exceptions
    throw UnimplementedError(
      'No failure mapping found for ${exception.runtimeType}',
    );
  }

  /// Parses Problem Details JSON from response body.
  static Map<String, dynamic> _parseProblemDetails(String body) {
    try {
      return jsonDecode(body) as Map<String, dynamic>;
    } catch (e) {
      return <String, dynamic>{};
    }
  }
}
