// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:cent16/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CountryModelAdapter());
    registerAdapter(FileModelAdapter());
    registerAdapter(PermissionModelAdapter());
    registerAdapter(RoleModelAdapter());
    registerAdapter(SessionStateModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserPreferencesModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CountryModelAdapter());
    registerAdapter(FileModelAdapter());
    registerAdapter(PermissionModelAdapter());
    registerAdapter(RoleModelAdapter());
    registerAdapter(SessionStateModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserPreferencesModelAdapter());
  }
}
